
spring:
  application:
    name: visrater-backend
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
  playground:
    cdn:
      version: latest
altair:
  enabled: true
  cdn:
    enabled: true
graphiql:
  enabled: true
  cdn:
    enabled: true
    version: 0.17.5
voyager:
  enabled: true
  cdn:
    enabled: true
graphql.playground:
  enabled: true
  cdn:
    enabled: true
spotify:
  client:
    id: 793c68b38b06461d8127f90148edc66a
    secret: c5c01048ed994710beb8f400fa676505
  accounts: 'https://accounts.spotify.com'
  api: 'https://api.spotify.com/v1'
