
spring:
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql:  true
  datasource:
    url: "jdbc:postgresql://localhost:5432/visual_rater"
    username: visual_rater_app
    password: seekthewolfinthyself
  application:
    name: visrater-backend
  graphql:
    websocket:
      path: /graphql
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET, POST
      max-age: 1800s
  servlet:
    multipart:
      enabled: true
      location: /tmp
  sql:
    init:
      mode: always
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
   root: ERROR
   org.spingframework.web: ERROR
   com.hawazin.visualraterspring: DEBUG
spotify:
  client:
    id: 793c68b38b06461d8127f90148edc66a
    secret: c5c01048ed994710beb8f400fa676505
  accounts: 'https://accounts.spotify.com'
  api: 'https://api.spotify.com/v1'
image-service:
  uri: 'http://localhost:7011'
